### ISSUE TITLE
Bump compat for Distributions to 0.25

### ISSUE THREAD

**Issue by ablaom** [SciML/PolyChaos.jl#71]
If an administrator could kick CompatHelper back to life, they can generate a PR (and see if there are any other out-of-data dependency compats)

This is needed downstream, for example for Surrogates.jl.

**Comment by ChrisRackauckas** [comment]
Fixed!

@JuliaRegistrator register()

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
