### ISSUE TITLE
404 on documentation link

### ISSUE THREAD

**Issue by abhijit-c** [SciML/PolyChaos.jl#74]
Hello,

I'm interested in using this package for a project of mine; however, when I try and follow the documentation links either through the README or in the about section, they lead to 404s. This is the link I'm attemping to follow:

[https://timueh.github.io/PolyChaos.jl/stable/](https://timueh.github.io/PolyChaos.jl/stable)

<img width="645" alt="Screen Shot 2022-04-29 at 12 44 36 PM" src="https://user-images.githubusercontent.com/14017302/165987912-79ac4377-50ac-41fa-8031-099f73435be8.png">

Did something break in a recent change?

**Comment by ranjanan** [comment]
We moved the repo. Tried to fix it in https://github.com/SciML/PolyChaos.jl/commit/209b3c9d55241f6a0ee0272e08ffb2f4f70fe039. Let's see if that worked.

**Comment by ChrisRackauckas** [comment]
Fixed.
